// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6224.PowerUp2;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSystemtopRight;
    public static SpeedController driveSystembottomRight;
    public static SpeedController driveSystemtopLeft;
    public static SpeedController driveSystembottomLeft;
    public static RobotDrive driveSystemRobotDrive;
    public static AnalogGyro driveSystemAnalogGyro;
    public static SpeedController elevatorelevatorVic;
    public static DoubleSolenoid clawclawVic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSystemtopRight = new VictorSP(0);
        LiveWindow.addActuator("DriveSystem", "topRight", (VictorSP) driveSystemtopRight);
        driveSystemtopRight.setInverted(false);
        driveSystembottomRight = new VictorSP(2);
        LiveWindow.addActuator("DriveSystem", "bottomRight", (VictorSP) driveSystembottomRight);
        driveSystembottomRight.setInverted(false);
        driveSystemtopLeft = new VictorSP(3);
        LiveWindow.addActuator("DriveSystem", "topLeft", (VictorSP) driveSystemtopLeft);
        driveSystemtopLeft.setInverted(false);
        driveSystembottomLeft = new VictorSP(4);
        LiveWindow.addActuator("DriveSystem", "bottomLeft", (VictorSP) driveSystembottomLeft);
        driveSystembottomLeft.setInverted(false);
        driveSystemRobotDrive = new RobotDrive(driveSystemtopLeft, driveSystembottomLeft,
              driveSystemtopRight, driveSystembottomRight);
        
        driveSystemRobotDrive.setSafetyEnabled(true);
        driveSystemRobotDrive.setExpiration(0.1);
        driveSystemRobotDrive.setSensitivity(0.5);
        driveSystemRobotDrive.setMaxOutput(1.0);

        driveSystemAnalogGyro = new AnalogGyro(0);
        LiveWindow.addSensor("DriveSystem", "AnalogGyro", driveSystemAnalogGyro);
        driveSystemAnalogGyro.setSensitivity(0.007);
        elevatorelevatorVic = new Spark(5);
        LiveWindow.addActuator("Elevator", "elevatorVic", (Spark) elevatorelevatorVic);
        elevatorelevatorVic.setInverted(false);
        clawclawVic = new DoubleSolenoid(0, 1, 2);
        LiveWindow.addActuator("Claw", "clawVic", clawclawVic);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
